# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod.name=Optiboxes
mod.id=optiboxes
mod.version=1.8
mod.group=btw.lowercase.optiboxes
mod.description=A skybox mod that allows you to use Optifine skies in Fabric 1.21+
mod.source=https://github.com/Legacy-Visuals-Project/Optiboxes
mod.issues=https://github.com/Legacy-Visuals-Project/Optiboxes/issues
mod.license=GPL-3.0-with-linking-exception
mod.modrinth=https://modrinth.com/mod/optiboxes
mod.curseforge=https://legacy.curseforge.com/minecraft/mc-mods/optiboxes
mod.discord=https://discord.gg/zqnXSUqedW

# Publishing
publish.modrinth=DWuwk8aA
publish.curseforge=1301799

# Dependencies
deps.fabric_loader_version=0.17.3
deps.mixinconstraints_version=1.1.0
deps.mixinsquared_version=0.2.0
deps.lightconfig=-SNAPSHOT
# 1.0-alpha.1 ---^

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.mc_version=[VERSIONED]
mod.mc_version_range=[VERSIONED]

# Versioned
deps.parchment_version=[VERSIONED]
deps.fabric_api_version=[VERSIONED]
deps.neoforge_version=[VERSIONED]
